// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

export interface Friend {
	id?: number
	friendUid?: string
	nickname?: string
	avatar?: string
	remark?: string
}

export interface FriendListReq {
}

export interface FriendListResp {
	list: Array<Friend>
}

export interface FriendPutInHandleReq {
	friendReqId?: number
	handleResult?: number // 处理结果
	handleMsg?: string
}

export interface FriendPutInHandleResp {
}

export interface FriendPutInListReq {
}

export interface FriendPutInListResp {
	list: Array<FriendRequest>
}

export interface FriendPutInReq {
	reqMsg?: string
	userId: string
}

export interface FriendPutInResp {
}

export interface FriendRequest {
	id?: number
	userId?: string
	reqUid?: string
	reqMsg?: string
	reqTime?: number
	handleResult?: number
	handleMsg?: string
}

export interface FriendsOnlineReq {
}

export interface FriendsOnlineResp {
	onLineList: { [key: string]: boolean }
}

export interface Group {
	id?: string
	name?: string
	icon?: string
	status?: number
	groupType?: number
	isVerify: boolean
	notification?: string
	notificationUid?: string
}

export interface GroupCreateReq {
	name?: string
	icon?: string
	isVerify?: boolean
}

export interface GroupCreateResp {
}

export interface GroupListReq {
}

export interface GroupListResp {
}
export interface GroupListRespParams {
	list: Array<Group>
}

export interface GroupMember {
	id?: number
	groupId?: string
	userId?: string
	nickname?: string
	userAvatarUrl?: string
	roleLevel?: number
	inviterUid?: string
	operatorUid?: string
}

export interface GroupPutInHandleReq {
	groupReqId?: number
	groupId?: string
	handleResult?: number // 处理结果
}

export interface GroupPutInHandleResp {
}

export interface GroupPutInListReq {
}
export interface GroupPutInListReqParams {
	groupId: string
}

export interface GroupPutInListResp {
	list?: Array<GroupRequest>
}

export interface GroupPutInReq {
	groupId?: string
	reqMsg?: string
	inviterUid?: string
	joinSource?: number
}

export interface GroupPutInResp {
}

export interface GroupRequest {
	id?: number
	userId?: string
	groupId?: string
	reqMsg?: string
	reqTime?: number
	joinSource?: number
	inviterUserId?: string
	handleUserId?: string
	handleTime?: number
	handleResult?: number
}

export interface GroupUserListReq {
}
export interface GroupUserListReqParams {
	groupId: string
}

export interface GroupUserListResp {
	list?: Array<GroupMember>
}

export interface GroupUserOnlineReq {
}
export interface GroupUserOnlineReqParams {
	groupId: string
}

export interface GroupUserOnlineResp {
	onLineList: { [key: string]: boolean }
}

