// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type Friend struct {
	Id        int64  `json:"id,omitempty"`
	FriendUid string `json:"friend_uid,omitempty"`
	Nickname  string `json:"nickname,omitempty"`
	Avatar    string `json:"avatar,omitempty"`
	Remark    string `json:"remark,omitempty"`
}

type FriendListReq struct {
}

type FriendListResp struct {
	List []*Friend `json:"list"`
}

type FriendPutInHandleReq struct {
	FriendReqId  int32  `json:"friend_req_id,omitempty"`
	HandleResult int32  `json:"handle_result,omitempty"` // 处理结果
	HandleMsg    string `json:"handle_msg,omitempty"`
}

type FriendPutInHandleResp struct {
}

type FriendPutInListReq struct {
}

type FriendPutInListResp struct {
	List []*FriendRequest `json:"list"`
}

type FriendPutInReq struct {
	ReqMsg string `json:"req_msg,omitempty"`
	UserId string `json:"user_id"`
}

type FriendPutInResp struct {
}

type FriendRequest struct {
	Id           int64  `json:"id,omitempty"`
	UserId       string `json:"user_id,omitempty"`
	ReqUid       string `json:"req_uid,omitempty"`
	ReqMsg       string `json:"req_msg,omitempty"`
	ReqTime      int64  `json:"req_time,omitempty"`
	HandleResult int    `json:"handle_result,omitempty"`
	HandleMsg    string `json:"handle_msg,omitempty"`
}

type Group struct {
	Id              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`
	Icon            string `json:"icon,omitempty"`
	Status          int64  `json:"status,omitempty"`
	GroupType       int64  `json:"groupType,omitempty"`
	IsVerify        bool   `json:"isVerify"`
	Notification    string `json:"notification,omitempty"`
	NotificationUid string `json:"notificationUid,omitempty"`
}

type GroupCreateReq struct {
	Name     string `json:"name,omitempty"`
	Icon     string `json:"icon,omitempty"`
	IsVerify bool   `json:"isVerify,optional,default=false"`
}

type GroupCreateResp struct {
}

type GroupListReq struct {
}

type GroupListResp struct {
	List []*Group `json:"list,omitempty"`
}

type GroupMember struct {
	Id            int64  `json:"id,omitempty"`
	GroupId       string `json:"groupId,omitempty"`
	UserId        string `json:"userId,omitempty"`
	Nickname      string `json:"nickname,omitempty"`
	UserAvatarUrl string `json:"userAvatar_url,omitempty"`
	RoleLevel     int    `json:"roleLevel,omitempty"`
	InviterUid    string `json:"inviterUid,omitempty"`
	OperatorUid   string `json:"operatorUid,omitempty"`
}

type GroupPutInHandleReq struct {
	GroupReqId   int32  `json:"groupReqId,omitempty"`
	GroupId      string `json:"groupId,omitempty"`
	HandleResult int32  `json:"handleResult,omitempty"` // 处理结果
}

type GroupPutInHandleResp struct {
}

type GroupPutInListReq struct {
	GroupId string `json:"groupId,omitempty"`
}

type GroupPutInListResp struct {
	List []*GroupRequest `json:"list,omitempty"`
}

type GroupPutInReq struct {
	GroupId    string `json:"groupId,omitempty"`
	ReqMsg     string `json:"reqMsg,omitempty"`
	InviterUid string `json:"inviterUid,omitempty,optional"`
	JoinSource int64  `json:"joinSource,omitempty"`
}

type GroupPutInResp struct {
}

type GroupRequest struct {
	Id            int64  `json:"id,omitempty"`
	UserId        string `json:"userId,omitempty"`
	GroupId       string `json:"groupId,omitempty"`
	ReqMsg        string `json:"reqMsg,omitempty"`
	ReqTime       int64  `json:"reqTime,omitempty"`
	JoinSource    int64  `json:"joinSource,omitempty"`
	InviterUserId string `json:"inviterUser_id,omitempty"`
	HandleUserId  string `json:"handleUser_id,omitempty"`
	HandleTime    int64  `json:"handleTime,omitempty"`
	HandleResult  int64  `json:"handleResult,omitempty"`
}

type GroupUserListReq struct {
	GroupId string `json:"groupId,omitempty"`
}

type GroupUserListResp struct {
	List []*GroupMember `json:"list,omitempty"`
}
